//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Contacto
{
	public virtual string Rut
	{
		get;
		set;
	}

	public virtual int idDireccion
	{
		get;
		set;
	}

	public virtual int TipoDireccion
	{
		get;
		set;
	}

	public virtual Persona Persona
	{
		get;
		set;
	}

}

