//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Direccion
{
	public virtual string Ciudad
	{
		get;
		set;
	}

	public virtual string Comuna
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual string Numero
	{
		get;
		set;
	}

}

