//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Persona
{
	public virtual string Rut
	{
		get;
		set;
	}

	public virtual string Nombre
	{
		get;
		set;
	}

	public virtual string ApellidoP
	{
		get;
		set;
	}

	public virtual string ApellidoM
	{
		get;
		set;
	}

	public virtual TipoPersona TipoPersona
	{
		get;
		set;
	}

}

