//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PersonaNatural : Persona
{
	private string nombres;

	private string apellidop;

	private string apellidom;

	public virtual string ApellidoM
	{
		get;
		set;
	}

	public virtual string ApellidoP
	{
		get;
		set;
	}

	public virtual string Nombres
	{
		get;
		set;
	}

	public virtual List<Direccion> Direccion
	{
		get;
		set;
	}

}

