//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Persona
{
	private string rut;

	public virtual string RUT
	{
		get;
		set;
	}

	public virtual string FormatoRut(string rutsinformato)
	{
		throw new System.NotImplementedException();
	}

}

